### ISSUE TITLE
Update To Django 3

### ISSUE THREAD

**Issue by 9mido** [macropin/django-googlebot#4]

**Comment by macropin** [comment]
Feel free to send a PR for this.

**Comment by 9mido** [comment]
I actually haven't tested this code it seemed like it has not been updated in a while which is why I made this issue. Maybe it does not need updating. Does this actually work in production and do what it says it does? 

I am thinking about using this. I don't want Google to mark me as a cloaking site if I don't use something like what this project advertises.

I see "Code written... completely untested :)" and it worries me a bit.

**Comment by macropin** [comment]
How about testing it with Django 3 and let me know how you go!

The initial code commit was 8 years ago, and it was untested at the time, but subsequently shown to work. But if you're concerned, check the license file for the warranty information.

**Comment by 9mido** [comment]
Ok fair enough.

Can you further explain what is the purpose of username='googlebot' and "Middleware to automatically log in the Googlebot with the user account 'googlebot'" means?

Do I have to make a user called 'googlebot' and provide credentials like a password to the 'googlebot' user? Do I have to make a username on django with https://stackoverflow.com/a/23482284 or python3 manage.py createsuperuser?

**Comment by macropin** [comment]
> Can you further explain what is the purpose of username='googlebot'

'googlebot' is just an arbitrary name to assign to the Googlebot user session. You could call it 'user123'.

>  "Middleware to automatically log in the Googlebot with the user account 'googlebot'" means?

It's in the title. It's a "Django middleware to allow googlebot to index logged-in accessible content".

> Do I have to make a user called 'googlebot' and provide credentials like a password to the 'googlebot' user?

No, see the usage of `get_or_create`:  https://github.com/macropin/django-googlebot/blob/master/googlebot/middleware.py#L21

If you want to know how it works, I suggest reading the code. It's only 29 lines. Also read the README. Some of your questions are answered there too.

**Comment by 9mido** [comment]
@macropin sorry but another question. How would you test this app to be sure that it worked?
